### ISSUE TITLE
Links for 204 site

### ISSUE THREAD

**Issue by HassanAkbar** [geolexica/isotc204.geolexica.org#3]
These are in about and feedback page of TC 211 site
1.
```
Identified issues that are publicly visible are maintained at the
https://github.com/ISO-TC211/TMG/issues[TMG GitHub Issues] page.
```

2.
```
The MLGT spreadsheet and corresponding documentation can be downloaded
from the
https://committee.iso.org/sites/tc211/home/re.html[ISO/TC 211 Resources page].
```

3.
```
The online version of ISO/TC 211 MLGT is jointly managed by the TMG and
https://www.ribose.com/[Ribose],
the official ISO/TC 211 web service provider and
Registration Authority of the
https://geodetic.isotc211.org/[ISO Geodetic Register].
```

4.
```
This is the feedback form link for 211

++++
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScdRwjGvHl1r4DamABqb1uQp7MQdsB-1s3vZHPBiKIKVNFMlQ/viewform?embedded=true" width="640" height="871" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
++++
```
Where can I find the corresponding links for TC 204 site?

5.
```
google_analytics:
  id: UA-168998071-2
```
This is the google analytics tag for `geolexica 211` site, should I use the same or different tag for `geolexica 204` site?

6.
```
social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374
```
And what are the social links for `geolexica 204` site?

_Originally posted by @HassanAkbar in https://github.com/geolexica/isotc204.geolexica.org/issues/1#issuecomment-1189017180_
